name: Android CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  android-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: ./.github/actions/setup-node

    - name: Install example node modules
      run: npm install
      working-directory: ./examples/GumTestApp/

    - name: Compile Android Example
      run: ./gradlew assembleDebug
      working-directory: ./examples/GumTestApp/android
